name: Demo books with Symfony + React + MySQL
description: This is a boilerplate for creating a new environment using PHP, Symfony, React (with Typescript) and MySQL. It contains a basic CRUD xample to demonstrate how components connect and make it easy to start with.
tags: [ php, symfony, react, typescript, mysql ]
icons: [ php, symfony, react, typescript, mysql ]
stack:
  packages:
    - name: PHP
      version: '8.2'
    - name: Symfony
      version: '6.2'
    - name: React
      version: '17'
    - name: Typescript
      version: '4.4'
    - name: MySQL
      version: '8.0'
discoverable: true
